"use strict";
var avlFunctions = require('./avlFunctions');

exports.dict = {
    'Digital Input 1': (value) => (value) ? {"value":"ON","unit": undefined} : {"value":"OFF","unit": undefined}, 
    'Digital Input 2': (value) => (value) ? {"value":"ON","unit": undefined} : {"value":"OFF","unit": undefined}, 
    'Digital Input 3': (value) => (value) ? {"value":"ON","unit": undefined} : {"value":"OFF","unit": undefined}, 
    'Pulse Counter Din1': (value) => {return{"value": value, "unit": undefined}}, 
    'Pulse Counter Din2': (value) => {return{"value": value, "unit": undefined}}, 
    'Analog Input 2': (value) => {return{"value": value * 0.001, "unit": "mV"}}, 
    'Authorized iButton': (value) => {return{"value": value, "unit": undefined}}, 
    'Analog Input 1': (value) => {return{"value": value * 0.001, "unit": "mV"}}, 
    'SD Status': (value,key) => (value) ? "Present" : "Not Present", 
    'ICCID1': (value) => {return{"value": value, "unit": undefined}}, 
    'Fuel Used GPS': (value) => {return{"value": value * 0.001, "unit": "l"}}, 
    'Fuel Rate GPS': (value) => {return{"value": value * 0.01, "unit": "l/100km"}}, 
    'ICCID2': (value) => {return{"value": value, "unit": undefined}}, 
    'Eco Score': (value) => {return{"value": value * 0.01, "unit": undefined}}, 
    'Total Odometer': (value) => {return{"value": value, "unit": undefined}}, 
    'Axis X': (value) => {return{"value": value, "unit": "mG"}}, 
    'Axis Y': (value) => {return{"value": value, "unit": "mG"}}, 
    'Axis Z': (value) => {return{"value": value, "unit": "mG"}}, 
    'BLE Battery #2': (value) => {return{"value": value, "unit": "%"}}, 
    'GSM Signal': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE Battery #3': (value) => {return{"value": value, "unit": "%"}}, 
    'BLE Battery #4': (value) => {return{"value": value, "unit": "%"}}, 
    'Speed': (value) => {return{"value": value, "unit": "km/h"}}, 
    'BLE Temperature #1': avlFunctions.bLETemperature, 
    'BLE Temperature #2': avlFunctions.bLETemperature, 
    'BLE Temperature #3': avlFunctions.bLETemperature, 
    'BLE Temperature #4': avlFunctions.bLETemperature, 
    'BLE Battery #1': (value) => {return{"value": value, "unit": "%"}}, 
    'Number of DTC': (value) => {return{"value": value, "unit": undefined}}, 
    'Engine Load': (value) => {return{"value": value, "unit": "%"}}, 
    'Coolant Temperature': (value) => {return{"value": value, "unit": "°C"}}, 
    'Short Fuel Trim': (value) => {return{"value": value, "unit": "%"}}, 
    'Fuel pressure': (value) => {return{"value": value, "unit": "kPa"}}, 
    'Intake MAP': (value) => {return{"value": value, "unit": "kPa"}}, 
    'Engine RPM': (value) => {return{"value": value, "unit": "rpm"}}, 
    'Vehicle Speed': (value) => {return{"value": value, "unit": "km/h"}}, 
    'Timing Advance': (value) => {return{"value": value, "unit": "°"}}, 
    'Intake Air Temperature': (value) => {return{"value": value, "unit": "°C"}}, 
    'MAF': (value) => {return{"value": value * 0.01, "unit": "g/sec"}}, 
    'Throttle Position': (value) => {return{"value": value, "unit": "%"}}, 
    'Runtime since engine start': (value) => {return{"value": value, "unit": "s"}}, 
    'Distance Traveled MIL On': (value) => {return{"value": value, "unit": "km"}}, 
    'Relative Fuel Rail Pressure': (value) => {return{"value": value * 0.1, "unit": "kPa"}}, 
    'Direct Fuel Rail Pressure': (value) => {return{"value": value * 10, "unit": "kPa"}}, 
    'Commanded EGR': (value) => {return{"value": value, "unit": "%"}}, 
    'EGR Error': (value) => {return{"value": value, "unit": "%"}}, 
    'Fuel Level': (value) => {return{"value": value, "unit": "%"}}, 
    'Distance Since Codes Clear': (value) => {return{"value": value, "unit": "km"}}, 
    'Barometic Pressure': (value) => {return{"value": value, "unit": "kPa"}}, 
    'Control Module Voltage': (value) => {return{"value": value * 0.001, "unit": "V"}}, 
    'Absolute Load Value': (value) => {return{"value": value, "unit": "%"}}, 
    'Ambient Air Temperature': (value) => {return{"value": value, "unit": "°C"}}, 
    'Time Run With MIL On': (value) => {return{"value": value, "unit": "min"}}, 
    'Time Since Codes Cleared': (value) => {return{"value": value, "unit": "min"}}, 
    'Absolute Fuel Rail Pressure': (value) => {return{"value": value * 0.1, "unit": "kPa"}}, 
    'Hybrid battery pack life': (value) => {return{"value": value, "unit": "%"}}, 
    'Engine Oil Temperature': (value) => {return{"value": value, "unit": "°C"}}, 
    'Fuel injection timing': (value) => {return{"value": value * 0.01, "unit": "°"}}, 
    'Fuel Rate': (value) => {return{"value": value * 0.01, "unit": "l/100km"}}, 
    'Geofence zone 06': avlFunctions.geofenceZone, 
    'Geofence zone 07': avlFunctions.geofenceZone, 
    'Geofence zone 08': avlFunctions.geofenceZone, 
    'Geofence zone 09': avlFunctions.geofenceZone, 
    'Geofence zone 10': avlFunctions.geofenceZone, 
    'External Voltage': (value) => {return{"value": value, "unit": "V"}}, 
    'Battery Voltage': (value) => {return{"value": value * 0.001, "unit": "V"}}, 
    'Battery Current': (value) => {return{"value": value * 0.001, "unit": "A"}}, 
    'GNSS Status': avlFunctions.gNSSStatus, 
    'Geofence zone 11': avlFunctions.geofenceZone, 
    'Dallas Temperature ID 4': (value) => {return{"value": value, "unit": undefined}}, 
    'Dallas Temperature 1': avlFunctions.dallasTemperature, 
    'Dallas Temperature 2': avlFunctions.dallasTemperature, 
    'Dallas Temperature 3': avlFunctions.dallasTemperature, 
    'Dallas Temperature 4': avlFunctions.dallasTemperature, 
    'Dallas Temperature ID 1': (value) => {return{"value": value, "unit": undefined}}, 
    'Dallas Temperature ID 2': (value) => {return{"value": value, "unit": undefined}}, 
    'iButton': (value) => {return{"value": value, "unit": undefined}}, 
    'Dallas Temperature ID 3': (value) => {return{"value": value, "unit": undefined}}, 
    'Data Mode': avlFunctions.dataMode, 
    'Vehicle Speed': (value) => {return{"value": value, "unit": "km/h"}}, 
    'Accelerator Pedal Position': (value) => {return{"value": value, "unit": "%"}}, 
    'Fuel Consumed': (value) => {return{"value": value * 0.1, "unit": "l"}}, 
    'Fuel level': (value) => {return{"value": value * 0.1, "unit": "l"}}, 
    'Engine RPM': (value) => {return{"value": value, "unit": "rpm"}}, 
    'BLE Humidity #1': (value) => {return{"value": value * 0.1, "unit": "%RH"}}, 
    'Total Mileage': (value) => {return{"value": value, "unit": "m"}}, 
    'Geofence zone 12': avlFunctions.geofenceZone, 
    'Fuel level': (value) => {return{"value": value, "unit": "%"}}, 
    'Door Status': avlFunctions.doorStatus, 
    'Geofence zone 13': avlFunctions.geofenceZone, 
    'Geofence zone 14': avlFunctions.geofenceZone, 
    'Geofence zone 15': avlFunctions.geofenceZone, 
    'Geofence zone 16': avlFunctions.geofenceZone, 
    'Geofence zone 17': avlFunctions.geofenceZone, 
    'Geofence zone 18': avlFunctions.geofenceZone, 
    'Geofence zone 19': avlFunctions.geofenceZone, 
    'Geofence zone 20': avlFunctions.geofenceZone, 
    'Geofence zone 21': avlFunctions.geofenceZone, 
    'Program Number': (value) => {return{"value": value, "unit": undefined}}, 
    'Module ID 8B': (value) => {return{"value": value, "unit": "min"}}, 
    'Engine Worktime': (value) => {return{"value": value, "unit": "min"}}, 
    'Engine Worktime (counted)': (value) => {return{"value": value, "unit": "min"}}, 
    'BLE Humidity #2': (value) => {return{"value": value * 0.1, "unit": "%RH"}}, 
    'Total Mileage (counted)': (value) => {return{"value": value, "unit": "m"}}, 
    'BLE Humidity #3': (value) => {return{"value": value * 0.1, "unit": "%RH"}}, 
    'Fuel Consumed(counted)': (value) => {return{"value": value * 0.1, "unit": "l"}}, 
    'BLE Humidity #4': (value) => {return{"value": value * 0.1, "unit": "%RH"}}, 
    'Fuel Rate': (value) => {return{"value": value * 0.1, "unit": "l/h"}}, 
    'AdBlue Level Percentage': (value) => {return{"value": value, "unit": "l"}}, 
    'AdBlue Level': (value) => {return{"value": value * 0.1, "unit": "%"}}, 
    'Battery Level': (value) => {return{"value": value, "unit": "%"}}, 
    'Engine Load': (value) => {return{"value": value, "unit": "%"}}, 
    'Engine Temperature': (value) => {return{"value": value * 0.1, "unit": "°C"}}, 
    'Axle 1 Load': (value) => {return{"value": value, "unit": "kg"}}, 
    'Axle 2 Load': (value) => {return{"value": value, "unit": "kg"}}, 
    'Axle 3 Load': (value) => {return{"value": value, "unit": "kg"}}, 
    'Axle 4 Load': (value) => {return{"value": value, "unit": "kg"}}, 
    'Axle 5 Load': (value) => {return{"value": value, "unit": "kg"}}, 
    'Control State Flags': (value) => {return{"value": value, "unit": undefined}}, 
    'Agricultural Machinery Flags': (value) => {return{"value": value, "unit": undefined}}, 
    'Harvesting Time': (value) => {return{"value": value, "unit": "min"}}, 
    'Area of Harvest': (value) => {return{"value": value, "unit": "m2"}}, 
    'LVC of Harvest': (value) => {return{"value": value, "unit": "m2/h"}}, 
    'Grain Mow Volume': (value) => {return{"value": value, "unit": "kg"}}, 
    'Grain Moisture': (value) => {return{"value": value, "unit": "%"}}, 
    'Harvesting Drum RPM': (value) => {return{"value": value, "unit": "rpm"}}, 
    'Gap Under Harvesting Drum': (value) => {return{"value": value, "unit": "rpm"}}, 
    'Security State Flags': (value) => {return{"value": value, "unit": "mm"}}, 
    'Tacho Total Distance': (value) => {return{"value": value, "unit": "m"}}, 
    'Trip Distance': (value) => {return{"value": value, "unit": "m"}}, 
    'Tacho Vehicle Speed': (value) => {return{"value": value, "unit": "km/h"}}, 
    'Tacho Driver Card Presence': (value) => {return{"value": value, "unit": undefined}}, 
    'Driver 1 States': (value) => {return{"value": value, "unit": undefined}}, 
    'Driver 2 States': (value) => {return{"value": value, "unit": undefined}}, 
    'Driver 1 Driving Time': (value) => {return{"value": value, "unit": "min"}}, 
    'Driver 2 Driving Time': (value) => {return{"value": value, "unit": "min"}}, 
    'Driver 1 Break Time': (value) => {return{"value": value, "unit": "min"}}, 
    'Driver 2 Break Time': (value) => {return{"value": value, "unit": "min"}}, 
    'Driver 1 Acitivity Duratation': (value) => {return{"value": value, "unit": "min"}}, 
    'Driver 2 Acitivity Duratation': (value) => {return{"value": value, "unit": "min"}}, 
    'Driver 1 Driving Time': (value) => {return{"value": value, "unit": "min"}}, 
    'Driver 2 Driving Time': (value) => {return{"value": value, "unit": "min"}}, 
    'Driver 1 ID High': (value) => {return{"value": value, "unit": undefined}}, 
    'Driver 1 ID Low': (value) => {return{"value": value, "unit": undefined}}, 
    'Driver 2 ID High': (value) => {return{"value": value, "unit": undefined}}, 
    'Driver 2 ID Low': (value) => {return{"value": value, "unit": undefined}}, 
    'Battery Temperature': (value) => {return{"value": value * 0.1, "unit": "°C"}}, 
    'Battery Level': (value) => {return{"value": value, "unit": "%"}}, 
    'Geofence zone 22': avlFunctions.geofenceZone, 
    'Geofence zone 23': avlFunctions.geofenceZone, 
    'Geofence zone 01': avlFunctions.geofenceZone, 
    'Geofence zone 02': avlFunctions.geofenceZone, 
    'Geofence zone 03': avlFunctions.geofenceZone, 
    'Geofence zone 04': avlFunctions.geofenceZone, 
    'Geofence zone 05': avlFunctions.geofenceZone, 
    'DTC Faults Count': (value) => {return{"value": value, "unit": undefined}}, 
    'Slope of Arm': (value) => {return{"value": value, "unit": "°"}}, 
    'Rotation of Arm': (value) => {return{"value": value, "unit": "°"}}, 
    'Eject of Arm': (value) => {return{"value": value, "unit": "m"}}, 
    'Horizontal Distance Arm': (value) => {return{"value": value, "unit": "m"}}, 
    'Height Arm Above Ground': (value) => {return{"value": value, "unit": "m"}}, 
    'Drill RPM': (value) => {return{"value": value, "unit": "rpm"}}, 
    'Spread Salt': (value) => {return{"value": value, "unit": "g/m2"}}, 
    'Battery Voltage': (value) => {return{"value": value, "unit": "V"}}, 
    'Spread Fine Grained Salt': (value) => {return{"value": value, "unit": "T"}}, 
    'Coarse Grained Salt': (value) => {return{"value": value, "unit": "T"}}, 
    'Spread DiMix': (value) => {return{"value": value, "unit": "T"}}, 
    'Spread Coarse Grained Calcium': (value) => {return{"value": value, "unit": "m3"}}, 
    'Spread Calcium Chloride': (value) => {return{"value": value, "unit": "m3"}}, 
    'Spread Sodium Chloride': (value) => {return{"value": value, "unit": "m3"}}, 
    'Auto Geofence': (value) => (value) ? {"value": "target entered zone", "unit": undefined} : {"value": "target left zone", "unit": undefined}, 
    'Spread Magnesium Chloride': (value) => {return{"value": value, "unit": undefined}}, 
    'Amount Of Spread Gravel': (value) => {return{"value": value, "unit": "T"}}, 
    'Amount Of Spread Sand': (value) => {return{"value": value, "unit": "T"}}, 
    'Digital Output 1': (value) => (value) ? "ON" : "OFF", 
    'Digital Output 2': (value) => (value) ? "ON" : "OFF", 
    'GNSS PDOP': (value) => {return{"value": value * 0.1, "unit": undefined}}, 
    'GNSS HDOP': (value) => {return{"value": value * 0.1, "unit": undefined}}, 
    'Width Pouring Left': (value) => {return{"value": value, "unit": "m"}}, 
    'Width Pouring Right': (value) => {return{"value": value, "unit": "m"}}, 
    'Salt Spreader Working Hours': (value) => {return{"value": value, "unit": "h"}}, 
    'Distance During Salting': (value) => {return{"value": value, "unit": "km"}}, 
    'Load Weight': (value) => {return{"value": value, "unit": "kg"}}, 
    'Retarder Load': (value) => {return{"value": value, "unit": "%"}}, 
    'Cruise Time': (value) => {return{"value": value, "unit": "min"}}, 
    'Geofence zone 24': avlFunctions.geofenceZone, 
    'Geofence zone 25': avlFunctions.geofenceZone, 
    'Geofence zone 26': avlFunctions.geofenceZone, 
    'Geofence zone 27': avlFunctions.geofenceZone, 
    'Geofence zone 28': avlFunctions.geofenceZone, 
    'Geofence zone 29': avlFunctions.geofenceZone, 
    'Geofence zone 30': avlFunctions.geofenceZone, 
    'Geofence zone 31': avlFunctions.geofenceZone, 
    'Geofence zone 32': avlFunctions.geofenceZone, 
    'Trip Odometer': (value) => {return{"value": value, "unit": "m"}}, 
    'Sleep Mode': avlFunctions.sleepMode, 
    'LLS 1 Fuel Level': (value) => {return{"value": value, "unit": "ltr"}}, 
    'LLS 1 Temperature': (value) => {return{"value": value, "unit": "°C"}}, 
    'LLS 2 Fuel Level': (value) => {return{"value": value, "unit": "ltr"}}, 
    'LLS 2 Temperature': (value) => {return{"value": value, "unit": "°C"}}, 
    'GSM Cell ID': (value) => {return{"value": value, "unit": undefined}}, 
    'GSM Area Code': (value) => {return{"value": value, "unit": undefined}}, 
    'RFID': (value) => {return{"value": value, "unit": undefined}}, 
    'Geofence zone 33': avlFunctions.geofenceZone, 
    'Geofence zone 34': avlFunctions.geofenceZone, 
    'LLS 3 Fuel Level': (value) => {return{"value": value, "unit": "ltr"}}, 
    'LLS 3 Temperature': (value) => {return{"value": value, "unit": "°C"}}, 
    'LLS 4 Fuel Level': (value) => {return{"value": value, "unit": "ltr"}}, 
    'LLS 4 Temperature': (value) => {return{"value": value, "unit": "°C"}}, 
    'LLS 5 Fuel Level': (value) => {return{"value": value, "unit": "ltr"}}, 
    'LLS 5 Temperature': (value) => {return{"value": value, "unit": "°C"}}, 
    'Geofence zone 35': avlFunctions.geofenceZone, 
    'Geofence zone 36': avlFunctions.geofenceZone, 
    'Geofence zone 37': avlFunctions.geofenceZone, 
    'Geofence zone 38': avlFunctions.geofenceZone, 
    'Geofence zone 39': avlFunctions.geofenceZone, 
    'Geofence zone 40': avlFunctions.geofenceZone, 
    'Geofence zone 41': avlFunctions.geofenceZone, 
    'Geofence zone 42': avlFunctions.geofenceZone, 
    'Geofence zone 43': avlFunctions.geofenceZone, 
    'Geofence zone 44': avlFunctions.geofenceZone, 
    'Geofence zone 45': avlFunctions.geofenceZone, 
    'Geofence zone 46': avlFunctions.geofenceZone, 
    'Geofence zone 47': avlFunctions.geofenceZone, 
    'Geofence zone 48': avlFunctions.geofenceZone, 
    'Geofence zone 49': avlFunctions.geofenceZone, 
    'Geofence zone 50': avlFunctions.geofenceZone, 
    'CNG status': (value) => {return{"value": value, "unit": undefined}}, 
    'CNG used': (value) => {return{"value": value, "unit": "kg"}}, 
    'CNG level': (value) => {return{"value": value, "unit": "%"}}, 
    'Engine Oil Level': (value) => {return{"value": value, "unit": undefined}}, 
    'Alarm': (value) => (value) ? "Alarm event occured" : "Reserved", 
    'Network Type': avlFunctions.networkType, 
    'User ID': (value) => {return{"value": value, "unit": undefined}}, 
    'Ignition': avlFunctions.ignition, 
    'Movement': avlFunctions.movement, 
    'Active GSM Operator': (value) => {return{"value": value, "unit": undefined}}, 
    'Green driving event duration': (value) => {return{"value": value, "unit": "ms"}}, 
    'Towing': (value) => (value) ? "towing" : "steady", 
    'Crash detection': avlFunctions.crashDetection, 
    'Immobilizer': avlFunctions.immobilizer, 
    'Jamming': (value) => (value) ? "jamming start" : "jamming stop", 
    'Trip': avlFunctions.trip,
    'Idling': (value) => (value) ? "idling" : "moving",
    'Unplug': (value) => (value) ? "battery unplugged" : "battery present", 
    'Green driving type': avlFunctions.greenDrivingType, 
    'Green Driving Value': (value) => {return{"value": value/100, "unit": "g"}}, 
    'Over Speeding': (value) => {return{"value": value, "unit": "km/h"}}, 
    'VIN': (value) => {return{"value": value, "unit": undefined}}, 
    'Crash trace data': (value) => {return{"value": value, "unit": undefined}}, 
    'EcoMaximum': (value) => {return{"value": value, "unit": undefined}}, 
    'EcoAverage': (value) => {return{"value": value, "unit": undefined}}, 
    'EcoDuration': (value) => {return{"value": value, "unit": "ms"}}, 
    'BT Status': avlFunctions.bTStatus, 
    'Barcode ID': (value) => {return{"value": value, "unit": undefined}}, 
    'Escort LLS Temperature #1': (value) => {return{"value": value, "unit": "°C"}}, 
    'BLE Fuel Level #1': (value) => {return{"value": value, "unit": undefined}}, 
    'Escort LLS Battery Voltage #1': (value) => {return{"value": value * 0.01, "unit": "V"}}, 
    'Escort LLS Temperature #2': (value) => {return{"value": value, "unit": "°C"}}, 
    'BLE Fuel Level #2': (value) => {return{"value": value, "unit": undefined}}, 
    'Escort LLS Battery Voltage #2': (value) => {return{"value": value * 0.01, "unit": "V"}}, 
    'Escort LLS Temperature #3': (value) => {return{"value": value, "unit": "°C"}}, 
    'BLE Fuel Level #3': (value) => {return{"value": value, "unit": undefined}}, 
    'Escort LLS Battery Voltage #3': (value) => {return{"value": value * 0.01, "unit": "V"}}, 
    'Escort LLS Temperature #4': (value) => {return{"value": value, "unit": "°C"}}, 
    'BLE Fuel Level #4': (value) => {return{"value": value, "unit": undefined}}, 
    'Escort LLS Battery Voltage #4': (value) => {return{"value": value * 0.01, "unit": "V"}}, 
    'Fault Codes': (value) => {return{"value": value, "unit": undefined}}, 
    'DTC Faults code': (value) => {return{"value": value, "unit": undefined}}, 
    'Driving State': avlFunctions.drivingState, 
    'Driving Records': (value) => {return{"value": value, "unit": undefined}}, 
    'Blood alcohol content': (value) => {return{"value": value, "unit": undefined}}, 
    'Instant Movement': (value) => (value) ? "movement on" : "movement off", 
    'Vehicle Range on Battery': (value) => {return{"value": value, "unit": "m"}}, 
    'Vehicle Range On Additional Fuel': (value) => {return{"value": value, "unit": "m"}}, 
    'BLE Fuel Frequency #1': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE Fuel Frequency #2': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE Fuel Frequency #3': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE Fuel Frequency #4': (value) => {return{"value": value, "unit": undefined}}, 
    'Crash event counter': (value) => {return{"value": value, "unit": undefined}}, 
    'VIN': (value) => {return{"value": value, "unit": undefined}}, 
    'UL202-02 Sensor Fuel level': (value) => {return{"value": value * 0.1, "unit": "mm"}}, 
    'BLE 1 Custom #1': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 2 Custom #1': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 3 Custom #1': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 4 Custom #1': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE Luminosity #1': (value) => {return{"value": value, "unit": "lx"}}, 
    'BLE Luminosity #2': (value) => {return{"value": value, "unit": "lx"}}, 
    'BLE Luminosity #3': (value) => {return{"value": value, "unit": "lx"}}, 
    'BLE Luminosity #4': (value) => {return{"value": value, "unit": "lx"}}, 
    'Digital output 3': (value) => (value) ? "ON" : "OFF", 
    'Ground Sense': (value) => (value) ? "ON" : "OFF", 
    'Beacon': (value) => {return{"value": value, "unit": undefined}}, 
    'ISO6709 Coordinates': (value) => {return{"value": value, "unit": undefined}}, 
    'Module ID 17B': (value) => {return{"value": value, "unit": undefined}}, 
    'OBD OEM Total Mileage': (value) => {return{"value": value, "unit": "km"}}, 
    'OBD OEM Fuel Level': (value) => {return{"value": value * 0.1, "unit": "l"}}, 
    'Private mode': (value) => (value) ? "Private mode on" : "Private mode off", 
    'Driver Name': (value) => {return{"value": value, "unit": undefined}}, 
    'Driver card license type': avlFunctions.driverCardLicenseType, 
    'Driver Gender': avlFunctions.driver, 
    'Driver Card ID': avlFunctions.driver, 
    'Driver Card Issue Year': (value) => {return{"value": value, "unit": undefined}}, 
    'Driver Card Issue Year': (value) => {return{"value": value, "unit": undefined}}, 
    'Driver Status Event': avlFunctions.driverStatusEvent, 
    'Ignition On Counter': (value) => (value) ? {"value":"Enable","unit": "s"} : {"value":"Disable","unit": "s"}, 
    'BLE 1 Custom #2': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 1 Custom #3': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 1 Custom #4': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 1 Custom #5': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 2 Custom #2': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 2 Custom #3': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 2 Custom #4': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 2 Custom #5': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 3 Custom #2': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 3 Custom #3': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 3 Custom #4': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 3 Custom #5': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 4 Custom #2': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 4 Custom #3': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 4 Custom #4': (value) => {return{"value": value, "unit": undefined}}, 
    'BLE 4 Custom #5': (value) => {return{"value": value, "unit": undefined}}, 
    'UL202-02 Sensor Status': (value) => {return{"value": value, "unit": undefined}}, 
    'SecurityStateFlags_P4': (value) => {return{"value": value, "unit": undefined}}, 
    'ControlStateFlags_P4': (value) => {return{"value": value, "unit": undefined}}, 
    'IndicatorStateFlags_P4': (value) => {return{"value": value, "unit": undefined}}, 
    'AgriculturalStateFlags_P4': (value) => {return{"value": value, "unit": undefined}}, 
    'UtilityStateFlags_P4': (value) => {return{"value": value, "unit": undefined}}, 
    'CisternStateFlags_P4': (value) => {return{"value": value, "unit": undefined}}, 
    'UMTS/LTE Cell ID': (value) => {return{"value": value, "unit": undefined}}, 
    'Total LNG Used': (value) => {return{"value": value, "unit": "kg"}}, 
    'Total LNG Used Counted': (value) => {return{"value": value, "unit": "kg"}}, 
    'LNG Level Proc': (value) => {return{"value": value, "unit": "%"}}, 
    'LNG Level kg': (value) => {return{"value": value, "unit": "kg"}}
};
